export const iconItems = [
              { icon: "shield-checkmark", text: "BH Y tế" },
              { icon: "list", text: "Cấp số STT" },
              { icon: "body", text: "BMI" },
              { icon: "heart", text: "Gợi ý vui" },
              { icon: "restaurant", text: "Thống kê" },
              { icon: "medkit", text: "Thuốc" },
              { icon: "water", text: "Uống nước" },
              { icon: "walk", text: "Tập luyện" },
              { icon: "bed", text: "Ngủ" },
              { icon: "alert", text: "Khẩn cấp" },
              { icon: "water", text: "Uống nước" },
              { icon: "walk", text: "Tập luyện" },
              { icon: "bed", text: "Ngủ" },
              { icon: "alert", text: "Khẩn cấp" },
              { icon: "water", text: "Uống nước" },
              { icon: "walk", text: "Tập luyện" },
              { icon: "bed", text: "Ngủ" },
              { icon: "alert", text: "Khẩn cấp" },
              { icon: "walk", text: "Tập luyện" },
              { icon: "bed", text: "Ngủ" },
              { icon: "alert", text: "Khẩn cấp" },
              { icon: "water", text: "Uống nước" },
              { icon: "walk", text: "Tập luyện" },
              { icon: "bed", text: "Ngủ" },
              { icon: "alert", text: "Khẩn cấp" }
];